### ISSUE TITLE
floating point exception, core dumped when player wears eyepatch

### ISSUE THREAD

**Issue by alarixnia** [2003scape/rsc-c#138]
```
(gdb) bt
#0  0x0000000000419476 in mudclient_draw_player (mud=0x7bb5818abcc0, x=-79, y=241, width=80, 
    height=121, id=2, skew_x=-53, ty=141, depth_top=0.993177354, depth_bottom=0.993177354)
    at src/mudclient.c:4587
#1  0x0000000000439aad in surface_draw_entity_sprite (surface=0x7bb580cbaf40, x=-79, y=241, 
    width=80, height=121, sprite_id=5002, tx=-53, ty=141, depth_top=0.992213666, 
    depth_bottom=0.994141042) at src/surface.c:2457
#2  0x000000000042f40e in scene_render_polygon_2d_face (scene=0x7bb58013ee80, face=2)
    at src/scene.c:1252
#3  0x0000000000433e27 in scene_gl_render (scene=0x7bb58013ee80) at src/scene.c:4167
#4  0x000000000042f88b in scene_render (scene=0x7bb58013ee80) at src/scene.c:1633
#5  0x000000000041ca8f in mudclient_draw_game (mud=0x7bb5818abcc0) at src/mudclient.c:5458
#6  0x000000000041d06d in mudclient_draw (mud=0x7bb5818abcc0) at src/mudclient.c:5603
#7  0x000000000041de21 in mudclient_run (mud=0x7bb5818abcc0) at src/mudclient.c:6794
#8  0x00000000004106c6 in mudclient_start_application (mud=0x7bb5818abcc0, 
    title=0x47b499 "Runescape by Andrew Gower") at src/mudclient.c:1290
#9  0x000000000041f1a2 in main (argc=1, argv=0x7f7fff8745e8) at src/mudclient.c:7223
```

```
(gdb) print sprite_id
$1 = 1415
(gdb) print animation_id
$2 = 163
```

**Comment by alarixnia** [comment]
cannot reproduce but i have the core file

**Comment by alarixnia** [comment]
can be reproduced when loading the game in f2p mode
