### ISSUE TITLE
SIGSEGV in mudclient_draw_experience_drops

### ISSUE THREAD

**Issue by alarixnia** [2003scape/rsc-c#81]
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000045d13c in mudclient_draw_experience_drops (mud=0x7d8b3155f940)
    at src/ui/experience-drops.c:29
29              sprintf(formatted_remainder, "%.2f",
[Current thread is 1 (process 5763)]
(gdb) bt
#0  0x000000000045d13c in mudclient_draw_experience_drops (mud=0x7d8b3155f940)
    at src/ui/experience-drops.c:29
#1  0x0000000000419f72 in mudclient_draw_ui (mud=0x7d8b3155f940) at src/mudclient.c:4638
#2  0x000000000041c821 in mudclient_draw_game (mud=0x7d8b3155f940) at src/mudclient.c:5287
#3  0x000000000041c913 in mudclient_draw (mud=0x7d8b3155f940) at src/mudclient.c:5342
#4  0x000000000041d61e in mudclient_run (mud=0x7d8b3155f940) at src/mudclient.c:6473
#5  0x0000000000410297 in mudclient_start_application (mud=0x7d8b3155f940, 
    title=0x47e8d1 "Runescape by Andrew Gower") at src/mudclient.c:1200
#6  0x000000000041e84a in main (argc=1, argv=0x7f7fffecbfd8) at src/mudclient.c:6880
```

**Comment by alarixnia** [comment]
==22195==ERROR: AddressSanitizer: dynamic-stack-buffer-overflow on address 0x7f7fffffe210 at pc 0x7f7ff6e46164 bp 0x7f
7fffffcc60 sp 0x7f7fffffc410 
WRITE of size 3 at 0x7f7fffffe210 thread T0
    #0 0x7f7ff6e46163 in memcpy (/usr/lib/libasan.so.5+0x46163)
    #1 0x7f7ff557e0b0 in __sfvwrite (/usr/lib/libc.so.12+0x17e0b0)
    #2 0x7f7ff555f6eb in __vfprintf_unlocked_l (/usr/lib/libc.so.12+0x15f6eb)
    #3 0x7f7ff555239c in _vsprintf_l (/usr/lib/libc.so.12+0x15239c)
    #4 0x7f7ff6e99269 in vsprintf (/usr/lib/libasan.so.5+0x99269)
    #5 0x7f7ff6e99644 in sprintf (/usr/lib/libasan.so.5+0x99644)
    #6 0x518543 in mudclient_draw_experience_drops /encrypt/home/nia/git/rsc-c/src/ui/experience-drops.c:39:9
    #7 0x43bd08 in mudclient_draw_ui /encrypt/home/nia/git/rsc-c/src/mudclient.c:4686:9
    #8 0x4503cb in mudclient_draw_game /encrypt/home/nia/git/rsc-c/src/mudclient.c:5335:5
    #9 0x451f9b in mudclient_draw /encrypt/home/nia/git/rsc-c/src/mudclient.c:5390:9
    #10 0x45265c in mudclient_run /encrypt/home/nia/git/rsc-c/src/mudclient.c:6525:9
    #11 0x452ffd in mudclient_start_application /encrypt/home/nia/git/rsc-c/src/mudclient.c:1215:5
    #12 0x453a7c in main /encrypt/home/nia/git/rsc-c/src/mudclient.c:6932:5
    #13 0x40339c in ___start /usr/src/lib/csu/common/crt0-common.c:350:2
